config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "events#index"

  resources :users, only: [:show]
  
  resources :events do 
    resources :races
  end

  resources :review, only: [:show, :edit, :update, :destroy]

  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :races, dependent: :destroy
  belongs_to :user
  has_one_attached :photo


  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/post.rb
class Post < ApplicationRecord

  validates :name, presence: true
  validates :description, presence: true
  validates :data, presence: true
end

app/models/race.rb
class Race < ApplicationRecord
  belongs_to :event
  has_one :user, through: :event
  has_many_attached :photos, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :date, presence: true
  validate :validate_photo_count

  def validate_photo_count
    if photos.attached? && photos.count > 4
      errors.add(:photos, "can't be more than 4")
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :events
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  
  include Pundit::Authorization

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index, :show]

  def index
    @events = policy_scope(Event)
    @user = current_user
  end

  def show 
    @event = Event.find(params[:id])
    authorize @event
  end

  def new
    @event = Event.new
    authorize @event
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    authorize @event
    
    if @event.save
      redirect_to event_path(@event)
    else
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
    authorize @event
  end

  def update
    @event = Event.find(params[:id])
    authorize @event

    if @event.update(event_params)
      redirect_to event_path(@event)
    else
      render :edit
    end
  end
  
  def destroy
    @event = Event.find(params[:id])
    authorize @event
    @event.destroy
  
    redirect_to events_path, status: :see_other
  end

  private

  def event_params
    params.require(:event).permit(:name, :photo)
  end
  
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  before_action :set_event, only: %i[new create edit update destroy]

  def index
    @event = Event.find(params[:event_id])
    @races = @event.races.includes(:photos)
  end

  def show
    @event = Event.find(params[:event_id])
    @race = @event.races.find(params[:id])
    authorize @race
  end

  def new 
    @event = Event.find(params[:event_id])
    @race = Race.new
    authorize @race
  end

  def create 
    @race = Race.new(race_params)
    @race.event = @event
    authorize @race

    if @race.save
      redirect_to event_path(@event)
    else
      render :new, status: :unprocessable_entity 
    end
  end

  def edit
    @race = Race.find(params[:id])
    authorize @race
  end

  def update
    @race = Race.find(params[:id])
    authorize @race

    if@race.update(race_params)
      redirect_to event_path(@race.event)
    else
      render :edit
    end
  end

  def destroy
    @race = Race.find(params[:id])
    authorize @event
    @race.destroy
    
    redirect_to event_path(@race.event), status: :see_other
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end

  def race_params
    params.require(:race).permit(:name, :address, :date, photos: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    authorize @user
    @events = @user.events
    @races = @user.events.map(&:races).flatten
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/edit.html.erb
<%= form_with model: @event, html: {class: "event-form"}, local: true do |f| %>
  <div class="form-group">
    <%= f.label :name, class: "form-label" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :photo, class: "form-label" %>
    <%= f.file_field :photo, class: "form-control" %>
  </div>
  <div class="form-group event-buttons">
    <%= f.submit "Save", class: "btn edit-button" %>
    <%= link_to "Delete",
      edit_event_path(@event),
      data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
      class: "btn btn-danger"
    %>
  </div>
<% end %>

app/views/events/index.html.erb
<div class="banner-container m-2">
  <div class="banner rounded">
    <%= image_tag "patrocinios.jpg", :class => "style_image" %>
  </div>
</div>


<div class="cards-container">
  <% @events.each do |event| %>
    <div class="event-card">
      <% if event.photo.attached? %>
        <%= cl_image_tag event.photo.key, :class => "event-image" %>
      <% end %>
      <%= link_to "", "events/#{event.id}", :class => "card_link" %>
      <div class="card-info">
        <h2><%= event.name %></h2>
        <div class="user-info">
          <%= image_tag "pts.jpg", :class => "user_photo" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/events/new.html.erb
<%= form_with model: @event, html: { class: "event-form" } do |f| %>
  <div class="form-group">
    <%= f.label :name, class: "form-label" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :photo, class: "form-label" %>
    <%= f.file_field :photo, class: "form-control" %>
  </div>
  <div class="form-group event-buttons">
    <%= f.submit "Save", class: "btn edit-button" %>
  </div>
<% end %>

app/views/events/show.html.erb
<main style="padding: 1rem; margin-top: 1rem;">
  <% if @event.races.nil? %>
    <h2> No Races...</h2>
  <% else %>
    <div class="button-container">
      <% if user_signed_in? && policy(@event).new? %>
        <%= link_to "New event", new_event_path, class: "btn btn-light" %>
      <% end %>
      <% if policy(@event).edit? %>
        <%= link_to "Edit this event", edit_event_path(@event), class: "btn btn-light" %>
      <% end %>
      <% if policy(@event).destroy? %>
        <%= button_to "Destroy this event", @event, method: :delete, class: "btn btn-danger", data: { confirm: 'Are you sure?' } %>
      <% end %>
      <% if user_signed_in? && policy(Race).create? %>
        <%= link_to "Create a new race", new_event_race_path(@event), class: "btn btn-light" %>
      <% end %>
    </div>

    <div class="d-flex justify-content-center mt-2 mb-2">
      <h2 class="font-weight-bold"> <%= @event.name %> </h2>
    </div>

    <div class="race-card-container">
      <% @event.races.each do |race| %>
        <div class="race-card">
          <% if race.photos.attached? %>
            <% race.photos.each do |photo| %>
              <%= cl_image_tag photo.key, class: "race-image" %>
            <% end %>
          <% end %>
        <div class="race-info">
          <h2 class="race-title"><%= race.name %></h2>
          <p class="race-address"> Address: <%= race.address %></p>
          <p class="race-date"> Date: <%= race.date.strftime("%A, %B %d, %Y") %></p>
          <div class="race-buttons-container">
            <% if policy(race).edit? %>
              <%= link_to "Edit this race", edit_event_race_path(@event, race.id), class: "race-button edit-button" %>
            <% end %>
            <%= button_to "Destroy this race", event_race_path(event_id: race.event_id, id: race.id), method: :delete, class: "race-button delete-button", data: { confirm: "Are you sure you want to delete this race?" } if policy(race).destroy? %>
          </div>
        </div>
      <%#= link_to "", event_race_path(event_id: race.event_id, id: race.id), class: "card_link" %>
      </div>
      <% end %>
    </div>
  <% end %>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pts</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body style="padding: 0;
  margin: 0;">
  <%= render "shared/navbar" %>
  <%= render "shared/flashes" %>
  <div style="min-height: 76vh;">
    <%= yield %>
  </div>
  <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/races/edit.html.erb
<div class="simple-form">
  <h1 class="d-flex justify-content-center mt-2 mb-2" >Edit Race</h1>
  <%= simple_form_for [@event, @race], html: { class: 'event-form' } do |f| %>
    <div class="form-group">
      <%= f.label :name, class: 'form-label' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :address, class: 'form-label' %>
      <%= f.text_field :address, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :date, class: 'form-label' %>
      <%= f.text_field :date, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    </div>
    <div class="event-buttons">
      <%= f.submit "Submit race", class: "btn edit-button" %>
    </div>
  <% end %>

</div>

app/views/races/new.html.erb
<div class="simple-form">
  <h1 class="form-label d-flex justify-content-center mt-2 mb-2 ">New race</h1>
  <%= simple_form_for [@event, @race], html: {class: "event-form"},  multipart: true do |f| %>
    <div class="form-group">
      <%= f.input :name, label_html: {class: "form-label"}, input_html: {class: "form-control"} %>
    </div>
    <div class="form-group">
      <%= f.input :address, label_html: {class: "form-label"}, input_html: {class: "form-control"} %>
    </div>
    <div class="form-group">
      <%= f.input :date, label_html: {class: "form-label"}, input_html: {class: "form-control"} %>
    </div>
    <div class="form-group">
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    </div>
    <div class="event-buttons">
      <%= f.submit "Submit race", class: "btn edit-button" %>
    </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path , class: "navbar-brand" do %>
      <%= image_tag "pts.jpeg" %> 
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Profile", user_path(current_user.id), class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "pts.jpeg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%#= link_to "Profile", user_path(current_user, query: ""), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<main style="padding: 1rem; margin-top: 1rem;">
  <div class="d-flex justify-content-center mt-2 mb-2">
    <h2 class="font-weight-bold"> <%= @user.first_name %> </h2>
  </div>

  <div class="row">
    <% if @events.any? %>
      <div class="col-md-6">
        <div class="text-center mb-3">
          <h3>Events</h3>
        </div>
        <div class="race-card-container">
          <% @events.each do |event| %>
            <div class="race-card">
              <% if event.photo.attached? %>
                <%= cl_image_tag event.photo.key, class: "race-image" %>
              <% end %>
              <div class="race-info">
                <h2 class="race-title"><%= event.name %></h2>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>

    <% if @races.any? %>
      <div class="col-md-6">
        <div class="text-center mb-3">
          <h3>Races</h3>
        </div>
        <div class="race-card-container">
          <% @races.each do |race| %>
            <div class="race-card">
              <% if race.photos.attached? %>
                <% race.photos.each do |photo| %>
                  <%= cl_image_tag photo.key, class: "race-image" %>
                <% end %>
              <% end %>
              <div class="race-info">
                <h2 class="race-title"><%= race.name %></h2>
                <p class="race-address"> Address: <%= race.address %></p>
                <p class="race-date"> Date: <%= race.date.strftime("%A, %B %d, %Y") %></p>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

  <% if @events.empty? && @races.empty? %>
    <p>No events or races to show.</p>
  <% end %>
</main>